env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: markscribe2
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  - builds:
      - markscribe2
    vendor: sheerlox
    homepage: "https://github.com/sheerlox/markscribe2"
    maintainer: "Pierre Cavin <me@sherlox.io>"
    description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
